import { useState, useEffect } from 'react'
import { supabase } from '../utils/supabaseClient'
import Auth from '../components/Auth'
import Account from '../components/Account'
import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
    const [session, setSession] = useState(null)


    useEffect(() => {
        setSession(supabase.auth.session())

        supabase.auth.onAuthStateChange((_event, session) => {
            setSession(session)
        })
    }, [])
    return (
        <div>
            <Head>
                <title>{!session ? "Sign In : SupaType" : "Profile : SupaType"}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            {!session ? <Auth /> : <Account key={session.user.id} session={session} />}
        </div>
    )
}