/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head"
import React, { useRef, useState, useEffect } from "react"
const getCloud = () => `oneplus apple motorola samsung nextjs react tailwind supabase supatype macbook phone bed clock speaker laptop`.split(" ")
import Timer from '../components/Timer'
import Word from '../components/Word'
function startType() {
  const [startCounting, setStartCounting] = useState(false);
  const [userInput, setUserInput] = useState("");
  const cloud = useRef(getCloud())
  const [activeWordIndex, setActiveWordIndex] = useState(0);
  const [correctWordArray, setCorrectWordArray] = useState([]);
  var processInput = (value) => {
    if (activeWordIndex === cloud.current.length) {
      return
    }
    if (!startCounting) {
      setStartCounting(true)
    }

    if (value.endsWith(" ")) {
      if (activeWordIndex === cloud.current.length - 1) {
        setStartCounting(false)
        setUserInput("Completed")
      }
      else {
        setUserInput('')
      }
      setActiveWordIndex(index => index + 1)
      setCorrectWordArray(data => {
        const word = value.trim()
        const newResult = [...data]
        newResult[activeWordIndex] = word === cloud.current[activeWordIndex]
        return newResult
      })
    }
    else {
      setUserInput(value)
    }
  }
  return (
    <>
      <Head>
        <title>New Typing Session</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='text-center min-h-screen md:block bg-[#1B2430]'>
        <span className="m-auto">
          <h1 className="text-white text-4xl">
            <Timer
              startCounting={startCounting}
              correctWords={correctWordArray.filter(Boolean).length}
            />
          </h1>
          <p className="text-white">
            {cloud.current.map((word, index) => {
              return <Word
                text={word}
                key={index}
                active={index === activeWordIndex}
                correct={correctWordArray[index]}
              />
            })}
          </p>
          <input type="text" value={userInput} onChange={(e) => processInput(e.target.value)} />
        </span>
      </section>
    </>
  )
}
export default startType